#!/bin/bash

c_platform_lines="$(wc -l src/platform/*/*.c src/platform/*/*.h | grep total | awk '{print $1}')"
c_common_lines="$(wc -l src/qcommon/*.c src/qcommon/*.h | grep total | awk '{print $1}')"
c_client_lines="$(wc -l src/client/*.c src/client/*.h | grep total | awk '{print $1}')"
c_server_lines="$(wc -l src/server/*.c src/server/*.h | grep total | awk '{print $1}')"
c_gamelib_lines="$(wc -l src/game/*.c src/game/*.h | grep total | awk '{print $1}')"
c_renderer_lines="$(wc -l src/ref_soft/*.c src/ref_soft/*.h | grep total | awk '{print $1}')"
let c_total_lines="$c_platform_lines + $c_common_lines + $c_client_lines + $c_server_lines + $c_gamelib_lines + $c_renderer_lines"

zig_platform_lines="$(wc -l src/platform/*/*.zig | grep total | awk '{print $1}')"
zig_common_lines="$(wc -l src/qcommon/*.zig | grep total | awk '{print $1}')"
zig_client_lines="$(wc -l src/client/*.zig | grep total | awk '{print $1}')"
zig_server_lines="$(wc -l src/server/*.zig | grep total | awk '{print $1}')"
zig_gamelib_lines="$(wc -l src/game/*.zig | grep total | awk '{print $1}')"
zig_renderer_lines="$(wc -l src/ref_soft/*.zig | grep total | awk '{print $1}')"
let zig_total_lines="$zig_platform_lines + $zig_common_lines + $zig_client_lines + $zig_server_lines + $zig_gamelib_lines + $zig_renderer_lines"

let platform_total="$c_platform_lines + $zig_platform_lines"
let common_total="$c_common_lines + $zig_common_lines"
let client_total="$c_client_lines + $zig_client_lines"
let server_total="$c_server_lines + $zig_server_lines"
let gamelib_total="$c_gamelib_lines + $zig_gamelib_lines"
let renderer_total="$c_renderer_lines + $zig_renderer_lines"
let final_total="$c_total_lines + $zig_total_lines"

let platform_percent="100 * $zig_platform_lines / $platform_total"
let common_percent="100 * $zig_common_lines / $common_total"
let client_percent="100 * $zig_client_lines / $client_total"
let server_percent="100 * $zig_server_lines / $server_total"
let gamelib_percent="100 * $zig_gamelib_lines / $gamelib_total"
let renderer_percent="100 * $zig_renderer_lines / $renderer_total"
let final_percent="100 * $zig_total_lines / $final_total"

echo ""
echo "==================== project porting status ===================="
echo "platform: $platform_total lines   | $zig_platform_lines zig : $c_platform_lines c   | $platform_percent% complete"
echo "common:   $common_total lines   | $zig_common_lines zig   : $c_common_lines c   | $common_percent% complete"
echo "client:   $client_total lines  | $zig_client_lines zig   : $c_client_lines c  | $client_percent% complete"
echo "server:   $server_total lines   | $zig_server_lines zig   : $c_server_lines c   | $server_percent% complete"
echo "gamelib:  $gamelib_total lines  | $zig_gamelib_lines zig   : $c_gamelib_lines c  | $gamelib_percent% complete"
echo "renderer: $renderer_total lines  | $zig_renderer_lines zig   : $c_renderer_lines c  | $renderer_percent% complete"
echo "total:    $final_total lines | $zig_total_lines zig : $c_total_lines c | $final_percent% complete"
echo "================================================================"
echo ""